### ISSUE TITLE
Filling with lava does not work

### ISSUE THREAD

**Issue by DogLoverPink** [TheGaming999/BlockChanger#4]
From what I can tell, using lava (Material.Lava) as the block to fill does not work.

I first tried this
`BlockChanger.setSectionCuboid(upperCorner, lowerCorner, new ItemStack(Material.GLASS), false);`
This worked fine, the section was filled with glass.

I then just changed the material type (nothing else), and it didn't work. Instead of filing with lava, it just filled with air.
`BlockChanger.setSectionCuboid(upperCorner, lowerCorner, new ItemStack(Material.LAVA), false);`

I also tried the asynchronous counterparts, and the SetCuboid() method to no avail.

**Server Info**
![image](https://github.com/TheGaming999/BlockChanger/assets/64995932/ddb58611-56dc-4217-8e2c-758af125c089)
 - Also tested on 1.19.3
- Latest version of BlockChanger

**Comment by Sandwichas** [comment]
Thanks for the report. I will look into it when I am free.

**Comment by Sandwichas** [comment]
Fixed [https://github.com/TheGaming999/BlockChanger/commit/d7c8134f89f1703eb0532a171a20540fa870f739](https://github.com/TheGaming999/BlockChanger/commit/d7c8134f89f1703eb0532a171a20540fa870f739)
